# Generated by Django 4.1.3 on 2023-01-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=300)),
                ('phone', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
